- hosts: ec2
  tasks:
  - name: Unable docker
    service:
     name: docker.service
     pattern: /usr/bin/docker
     enabled: false
     state: stopped
    become: true

  - name: Install Apache, Git
    yum:
      name: httpd, git
      state: present
      update_cache: yes
    become: true

  - name: Enable Apache
    service:
      name: httpd
      enabled: yes
    become: true

  - name: Install app
    copy:
     src: ../hello-2048/public_html/
     dest: /var/www/html/
     owner: apache
     group: apache
     mode: "0644"
     directory_mode: "0755"
    become: true

